### ISSUE TITLE
Exception: No supported browser found or issue with cookie extraction

### ISSUE THREAD

**Issue by MrTimonM** [codeEye0123/chatGPT_telegram_bot#1]
Hi, I have chrome installed yet I see this error.
Exception: No supported browser found or issue with cookie extraction

**Comment by codeEye0123** [comment]
Thank you for your report.
This error occurs because you are using the Chrome browser.
Please use the Firefox browser.
First, you need to sign up for bard in the Firefox browser and send at least one question.
Then, It will work normally even if you turn off the browser and run the program.
Plz try it.
